### ISSUE TITLE
About Checkpoints

### ISSUE THREAD

**Issue by lsyysl9711** [RoyalSkye/Routing-MVMoE#1]
Thanks for sharing checkpoints and codes! 

However, checkpoints for POMO-CVRP can't be loaded into any models since mismatch between tensors. 

In MLTEncoder, to encode location/demand information, codes will use nn.Embedding(5,128). However, in the checkpoint POMO-CVRP.pt, the shape is nn.Embedding(3,128). So there is a mismatch.

**Comment by RoyalSkye** [comment]
Hi there, POMO-CVRP is a single-task solver rather than a multi-task solver. Could you try to set --problem="CVRP", --model_type="SINGLE"?

**Comment by lsyysl9711** [comment]
Thanks for mentioning me this! I will try it!
