### ISSUE TITLE
About Pre-trained Models

### ISSUE THREAD

**Issue by lsyysl9711** [RoyalSkye/Routing-MVMoE#2]
Thanks for sharing the pre-trained models.

But in the pretrained directory, I only saw two POMO based neural solvers: "POMO-CVRP" and "POMO-VRPTW". In the paper, there should be another four single models: POMO-OVRP, POMO-VRPL, POMO-VRPB, POMO-OVRPTW. I really appreciate if you could release them as well.

**Comment by RoyalSkye** [comment]
Unfortunately, these single-task models are not available😐. They can be obtained by running `train.py`.
